server:
  port: 8443

spring:
  datasource:
    username: root
    password: Zbawq123.
    url: jdbc:mysql://localhost:3306/white_jotter?useUnicode=true&characterEncoding=utf8&serverTimezone=Hongkong
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  type-aliases-package: top.zbawq.pojo



  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
        #驼峰下划线转换
      column-underline: true
        #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    refresh: false
  configuration:
#是否开启自动驼峰命名规则（camel case）映射
    map-underscore-to-camel-case: true
#开启Mybatis二级缓存，默认为 true。
    cache-enabled: false


